### ISSUE TITLE
did you test this kernel on 8860U?

### ISSUE THREAD

**Issue by nmocruz** [ljrk0/android_kernel_coolpad_8860U#1]
Hi, 
I am tryng to build a cynamodgen port or build a rom to this model,
I dont have any experience with install a new OS in android device. 
did you test this kernel on 8860U?

**Comment by ljrk0** [comment]
Sadly no, shortly after I had the device for testing the original owners needed it back. So it now only functions as a faster source-host, sorry :/

**Comment by nmocruz** [comment]
I will try to not brick my phone.

**Comment by ljrk0** [comment]
good luck!
